spring:
  application:
    name: "profile"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "123"
  jpa:
    hibernate.ddl-auto: "update"
    show-sql: true
  profiles:
    active: "dev"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
server:
  port: 8081
  url: "http://localhost:${server.port}"
accounts:
  message: "Card server message 1234"
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
