### Create card
POST localhost:8082/api/v1/card
Content-Type: application/json

{
  "phoneNumber": "998910171212",
  "amount": 5700,
  "ownerId": "dfd43779-afd4-4c73-9ebd-4b233aec641e"
}

### Get card list by phoneNumber
GET localhost:8082/api/v1/card/phone/998910171231
correlation-id: "asdasdas"