spring:
  application:
    name: "notification"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "123"
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
  profiles:
    active: "dev"
accounts:
  message: "Card server message 1234"
server:
  port: 8084
  url: "http://localhost:${server.port}"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/